before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
language: ruby
rvm:
  - "2.2.0"
services:
  - mongodb
  - redis-server
addons:
  code_climate:
    repo_token: 26c6dd1f95ebc2a15d4c123b3d8a5cfae3bac0462ebdf60c6a090b893b0c5bd0
script:
  - cd dummy
  - ln -s ../.git .git
  - cp config/database.travis.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:create
  - bundle exec rake db:test:prepare
  - CODECLIMATE_REPO_TOKEN=26c6dd1f95ebc2a15d4c123b3d8a5cfae3bac0462ebdf60c6a090b893b0c5bd0 bundle exec rspec
  - CODECLIMATE_REPO_TOKEN=26c6dd1f95ebc2a15d4c123b3d8a5cfae3bac0462ebdf60c6a090b893b0c5bd0 bundle exec cucumber
